name: Corriger un article
description: Apporter une correction ou une précision à propos d'un article
labels: ['Amélioration']
body:
  - type: input
    id: url-article
    attributes:
      label: URL de l'article concerné
    validations:
      required: true
  - type: textarea
    attributes:
      label: À propos de cet article
      description: 'Écrivez ce que vous souhaiteriez modifier ci-dessous'
    validations:
      required: true
